### ISSUE TITLE
Automatic linking when syntax highlighting

### ISSUE THREAD

**Issue by hadley** [r-lib/hugodown#17]
Need to post process to:

1. Convert .md to .json ast using pandoc
2. Read json into R, then apply pkgdown highlighting to each code chunk
3. Convert back to .json

Note that goldmark does not preserve raw html (like pandoc does), so it would need to include a shortcode in the output, along the lines of https://anaulin.org/blog/hugo-raw-html-shortcode/

**Comment by maelle** [comment]
If Hugo gains a Markdown render hook for code blocks, wouldn't that be easier to use that?

**Comment by hadley** [comment]
@maelle sure it might be easier, but it'll mean that you no longer get netlify deploy previews on PRs.

**Comment by maelle** [comment]
I don't understand why? Markdown render hooks are a Hugo thing.

**Comment by hadley** [comment]
Because the syntax highlighting has to be done by R, because that's how you get all the pkgdown magic.

**Comment by jemus42** [comment]
@maelle Using data templates to store the urls would probably require storing one key per package and then one url per function, something like this:

```yaml
ggplot2:
  url: https://ggplot2.tidyverse.org/
  functions:
    annotate: https://ggplot2.tidyverse.org/reference/annotate.html
    geom_bar: https://ggplot2.tidyverse.org/reference/geom_bar.html
    geom_col: https://ggplot2.tidyverse.org/reference/geom_bar.html
```

(presumably omitting the base url from the function links)

You can "guess" the correct url to the function's documentation on a pkgdown site, but that only works if the function's associated `.Rd` has the same name as the function.  
This fails in the case of `geom_bar()` and `geom_col()` there, which is why at least "pkgdown site url + package name + function name" are not enough information :/

I like the idea of using data templates for a plain-Hugo compatible way of linking to packages without further R intervention (after knitting), but I'm not sure how far this will take us with regard to autolinking for functions because of this.  

Generating the data into `/data/` on-demand at knit-time (or in a dedicated step?) sounds a lot better than my previous attempts at the matter though, but I only wanted to link to packages so far.

**Comment by jemus42** [comment]
Re: `goldmark` not preserving raw HTML: This is the default, but not only behavior. I tried the example from the linked blog post and included the following in a plain `.md` post rendered by goldmark:

```html
<p class="speshal-fancy-custom">
    This is <strong>raw HTML</strong>, inside Markdown.
</p>
```

And the output is rendered correctly:
![image](https://user-images.githubusercontent.com/1613346/83034664-c744a980-a038-11ea-8617-cd283e7cd392.png)

I think the relevant bit there is the [`unsafe`](https://gohugo.io/getting-started/configuration-markup#goldmark) setting in the `goldmark` config in my `config.toml`:

> **unsafe**
> By default, Goldmark does not render raw HTMLs and potentially dangerous links. If you have lots of inline HTML and/or JavaScript, you may need to turn this on.

```toml
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
```

That way you would have to insist on this configuration, but would get away without an extra shortcode.
