### ISSUE TITLE
Academic syntax highlighting in dark mode

### ISSUE THREAD

**Issue by hadley** [r-lib/hugodown#34]
* Find academic syntax highlighting css
* Convert class names to chroma names

**Comment by hadley** [comment]
`_root.scss` has

```scss
pre,
code {
  font-family: $sta-font-mono, monospace;
  color: #c7254e;
  background-color: #f9f2f4;
}

pre {
  margin: 0 0 1rem 0;
  background-color: rgb(248, 248, 248); /* Match default highlight theme. */
  border-color: rgb(248, 248, 248);
  font-size: 0.7rem;
  border-radius: 4px;
}

pre code {
  white-space: pre; /* Override Bootstrap to preserve line breaks in code. */
  overflow-x: auto;
}
```
