### ISSUE TITLE
Option to turn off downlit?

### ISSUE THREAD

**Issue by njtierney** [r-lib/hugodown#37]
Could `md_document` gain an argument to not apply `downlit` ?

There was previously an option with [`hugo_document` to switch on `downlit`](https://github.com/r-lib/hugodown/blob/283750354f21f24686b6a4173bf79264f4cc1a9e/R/hugo-format.R#L23)

However it looks like that option has been removed now in [`md_document`](https://github.com/r-lib/hugodown/blob/master/R/hugo-format.R).

While I think that downlit is awesome, and I love the idea, at the moment I don't want to generate links to functions, as it seems to change the colours I get. Here's an example of what I meant:

Compare using downlit (from `md_document`) in [this post](https://www.njtierney.com/post/2020/06/08/jq-rowwise-median/)

![image](https://user-images.githubusercontent.com/6488485/84043549-c709be00-a9e9-11ea-96ae-c24e9d90e349.png)

To not downlit (from `hugo_document`) in [this post](https://www.njtierney.com/post/2020/06/01/tidy-anscombe/)

![image](https://user-images.githubusercontent.com/6488485/84043580-d0932600-a9e9-11ea-8d14-2fb1c3e59144.png)

I think that this issue with syntax highlight maybe has to do with `downlit` being used? 

I have tried to follow the [config guidelines](https://hugodown.r-lib.org/articles/config.html) as close as I could, but perhaps I've missed something in [my blog set](https://github.com/rbind/njtierney.com).

**Comment by hadley** [comment]
I'd rather fixing the underlying problem than giving you the ability to turn it off (although it's probably worth doing that eventually, I'd prefer to force myself to confront highlight issues at the moment). 

Also in the second post, I see: 
<img width="753" alt="Screenshot 2020-06-08 at 11 01 52 AM" src="https://user-images.githubusercontent.com/4196/84053408-78234080-a977-11ea-9b72-4fd471bce2e0.png">

So there may be other issues.

Have you added the chroma classes to your css?

**Comment by njtierney** [comment]
Fair enough! Syntax highlighting is hard, thanks for taking this on.

It looks like I may have introduced some issues, perhaps. Between now and then I have updated `config.toml` to add `pygmentsUseClasses = true`.

I ran `hugo gen chromastyles --style=monokai` on the command line and wasn't really paying attention - it generated some nice css for me, but I guess I was kind of half expecting that it would add this to my repo in the right spot automagically (too many expectations from how `usethis` works perhaps!)

So perhaps I'm just missing all the CSS? If so, is it expecting a special name of the CSS file and where should it live?

```css
/* Background */ .chroma { color: #f8f8f2; background-color: #272822 }
/* Other */ .chroma .x {  }
/* Error */ .chroma .err { color: #960050; background-color: #1e0010 }
/* LineTableTD */ .chroma .lntd { vertical-align: top; padding: 0; margin: 0; border: 0; }
/* LineTable */ .chroma .lntable { border-spacing: 0; padding: 0; margin: 0; border: 0; width: auto; overflow: auto; display: block; }
/* LineHighlight */ .chroma .hl { display: block; width: 100%;background-color: #ffffcc }
/* LineNumbersTable */ .chroma .lnt { margin-right: 0.4em; padding: 0 0.4em 0 0.4em;color: #7f7f7f }
/* LineNumbers */ .chroma .ln { margin-right: 0.4em; padding: 0 0.4em 0 0.4em;color: #7f7f7f }
/* Keyword */ .chroma .k { color: #66d9ef }
/* KeywordConstant */ .chroma .kc { color: #66d9ef }
/* KeywordDeclaration */ .chroma .kd { color: #66d9ef }
/* KeywordNamespace */ .chroma .kn { color: #f92672 }
/* KeywordPseudo */ .chroma .kp { color: #66d9ef }
/* KeywordReserved */ .chroma .kr { color: #66d9ef }
/* KeywordType */ .chroma .kt { color: #66d9ef }
/* Name */ .chroma .n {  }
/* NameAttribute */ .chroma .na { color: #a6e22e }
/* NameBuiltin */ .chroma .nb {  }
/* NameBuiltinPseudo */ .chroma .bp {  }
/* NameClass */ .chroma .nc { color: #a6e22e }
/* NameConstant */ .chroma .no { color: #66d9ef }
/* NameDecorator */ .chroma .nd { color: #a6e22e }
/* NameEntity */ .chroma .ni {  }
/* NameException */ .chroma .ne { color: #a6e22e }
/* NameFunction */ .chroma .nf { color: #a6e22e }
/* NameFunctionMagic */ .chroma .fm {  }
/* NameLabel */ .chroma .nl {  }
/* NameNamespace */ .chroma .nn {  }
/* NameOther */ .chroma .nx { color: #a6e22e }
/* NameProperty */ .chroma .py {  }
/* NameTag */ .chroma .nt { color: #f92672 }
/* NameVariable */ .chroma .nv {  }
/* NameVariableClass */ .chroma .vc {  }
/* NameVariableGlobal */ .chroma .vg {  }
/* NameVariableInstance */ .chroma .vi {  }
/* NameVariableMagic */ .chroma .vm {  }
/* Literal */ .chroma .l { color: #ae81ff }
/* LiteralDate */ .chroma .ld { color: #e6db74 }
/* LiteralString */ .chroma .s { color: #e6db74 }
/* LiteralStringAffix */ .chroma .sa { color: #e6db74 }
/* LiteralStringBacktick */ .chroma .sb { color: #e6db74 }
/* LiteralStringChar */ .chroma .sc { color: #e6db74 }
/* LiteralStringDelimiter */ .chroma .dl { color: #e6db74 }
/* LiteralStringDoc */ .chroma .sd { color: #e6db74 }
/* LiteralStringDouble */ .chroma .s2 { color: #e6db74 }
/* LiteralStringEscape */ .chroma .se { color: #ae81ff }
/* LiteralStringHeredoc */ .chroma .sh { color: #e6db74 }
/* LiteralStringInterpol */ .chroma .si { color: #e6db74 }
/* LiteralStringOther */ .chroma .sx { color: #e6db74 }
/* LiteralStringRegex */ .chroma .sr { color: #e6db74 }
/* LiteralStringSingle */ .chroma .s1 { color: #e6db74 }
/* LiteralStringSymbol */ .chroma .ss { color: #e6db74 }
/* LiteralNumber */ .chroma .m { color: #ae81ff }
/* LiteralNumberBin */ .chroma .mb { color: #ae81ff }
/* LiteralNumberFloat */ .chroma .mf { color: #ae81ff }
/* LiteralNumberHex */ .chroma .mh { color: #ae81ff }
/* LiteralNumberInteger */ .chroma .mi { color: #ae81ff }
/* LiteralNumberIntegerLong */ .chroma .il { color: #ae81ff }
/* LiteralNumberOct */ .chroma .mo { color: #ae81ff }
/* Operator */ .chroma .o { color: #f92672 }
/* OperatorWord */ .chroma .ow { color: #f92672 }
/* Punctuation */ .chroma .p {  }
/* Comment */ .chroma .c { color: #75715e }
/* CommentHashbang */ .chroma .ch { color: #75715e }
/* CommentMultiline */ .chroma .cm { color: #75715e }
/* CommentSingle */ .chroma .c1 { color: #75715e }
/* CommentSpecial */ .chroma .cs { color: #75715e }
/* CommentPreproc */ .chroma .cp { color: #75715e }
/* CommentPreprocFile */ .chroma .cpf { color: #75715e }
/* Generic */ .chroma .g {  }
/* GenericDeleted */ .chroma .gd { color: #f92672 }
/* GenericEmph */ .chroma .ge { font-style: italic }
/* GenericError */ .chroma .gr {  }
/* GenericHeading */ .chroma .gh {  }
/* GenericInserted */ .chroma .gi { color: #a6e22e }
/* GenericOutput */ .chroma .go {  }
/* GenericPrompt */ .chroma .gp {  }
/* GenericStrong */ .chroma .gs { font-weight: bold }
/* GenericSubheading */ .chroma .gu { color: #75715e }
/* GenericTraceback */ .chroma .gt {  }
/* GenericUnderline */ .chroma .gl {  }
/* TextWhitespace */ .chroma .w {  }
```
